In [1]:
import numpy as np

# Numpy Arrays for Algebra Operations

In [2]:
# Multiply a vector or matrix by a scalar, using multiplication between the NumPy array and the scalar:
matrix = np.array([[1,2],[3,4]])
4 * matrix 

array([[ 4,  8],
       [12, 16]])

In [3]:
# Adding equally sized vectors or matrices, using addition between the NumPy arrays:
matrix_1 = np.array([[1,2],[3,4]])
matrix_2 = np.array([[-4,-3],[-2,-1]])
matrix_1 + matrix_2

array([[-3, -1],
       [ 1,  3]])

In [4]:
# Vector dot products can be computed using the np.dot() function:
v1 = np.array([-1,-2,-3])
v2 = np.array([2,2,2])
np.dot(v1,v2) 

-12

In [5]:
# Matrix multiplication is computed using either the np.matmul() function or using the @ symbol as shorthand:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[-4,-3],[-2,-1]])
 
# one way to matrix multiply
np.matmul(m1,m2)
# another way to matrix multiply
m1@m2

array([[ -8,  -5],
       [-20, -13]])