In [1]:
import numpy as np

## NumPy Arrays

In [2]:
# NumPy array representation of a vector:
vector = v = np.array([1, 2, 3, 4, 5, 6])
print(vector) 

[1 2 3 4 5 6]


In [3]:
# Create a matrix, which is the equivalent of a two-dimensional NumPy array
matrix = np.array([[1,2],[3,4]])
print(matrix) 

[[1 2]
 [3 4]]


In [4]:
# Create a matrix by combining existing vectors using the np.column_stack() function:
v1 = np.array([-2,-2,-2,-2])
v2 = np.array([0,0,0,0])
v3 = np.array([3,3,3,3])
 
vector_stack = np.column_stack((v1, v2, v3))
print(vector_stack) 

[[-2  0  3]
 [-2  0  3]
 [-2  0  3]
 [-2  0  3]]


In [5]:
# Access the shape of a matrix or vector once it’s been created as a NumPy array, by calling the .shape attribute of the array variable:
matrix_shape = np.array([[1,2],[3,4]])
print(matrix_shape.shape)

(2, 2)


In [6]:
# Access individual elements in a NumPy array by indexing all dimensions in a single square bracket, separating the dimension indices with commas:
matrix = np.array([[1,2],[3,4]])
print(matrix[0,1])

2


In [7]:
# Select a subset or entire dimension of a NumPy array using a colon:
matrix = np.array([[1,2],[3,4]])
print(matrix[:,1]) 

[2 4]
