In [1]:
import numpy as np

# Special Matricies

In [ ]:
# An identity matrix can be constructed using the np.eye() functions, which takes an integer argument that determines the n x n size of the square identity matrix:
# 4x4 identity matrix
identity = np.eye(4)
print(identity)

In [5]:
# A matrix or vector of all zeros can be constructed using the np.zeros() function, which takes in a tuple argument for the shape of the NumPy array filled with zeros:

# 5-element vector of zeros
zero_vector = np.zeros((5))
print(zero_vector)

# 3x2 matrix of zeros
zero_matrix = np.zeros((3,2))
print(zero_matrix)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
# The transpose of a matrix can be accessed using the .T attribute of a NumPy array as shown below:
A = np.array([[1,2],[3,4]])
A_transpose = A.T

# since A_transpose is the transpose of A, the rows and columns are swapped.
print(A_transpose) 

[[1 3]
 [2 4]]
